package scxmlgen.Modalities;

import genfusionscxml.GenFusionSCXML;
import scxmlgen.interfaces.IOutput;



public enum Output implements IOutput{
    //weather days week
    WEATHER_DAYSWEEK_DOMINGO("[WEATHER][TYPE1][dayOfWeek][domingo][0]"),
    WEATHER_DAYSWEEK_SEGUNDA("[WEATHER][TYPE1][dayOfWeek][segunda][1]"),
    WEATHER_DAYSWEEK_TERCA("[WEATHER][TYPE1][dayOfWeek][terça][2]"),
    WEATHER_DAYSWEEK_QUARTA("[WEATHER][TYPE1][dayOfWeek][quarta][3]"),
    WEATHER_DAYSWEEK_QUINTA("[WEATHER][TYPE1][dayOfWeek][quinta][4]"),
    WEATHER_DAYSWEEK_SEXTA("[WEATHER][TYPE1][dayOfWeek][sexta][5]"),
    WEATHER_DAYSWEEK_SABADO("[WEATHER][TYPE1][dayOfWeek][sábado][6]"),
    //weather days rel
    WEATHER_DAYSREL_TODAY("[WEATHER][TYPE1][today][today][]"),
    WEATHER_DAYSREL_TOMORROW("[WEATHER][TYPE1][tomorrow][tomorrow][]"),
    //weather days number
    
    WEATHER_DAYSNUMBER_1("[WEATHER][TYPE1][numberOfDay][1][]"),
    WEATHER_DAYSNUMBER_2("[WEATHER][TYPE1][numberOfDay][2][]"),
    WEATHER_DAYSNUMBER_3("[WEATHER][TYPE1][numberOfDay][3][]"),
    WEATHER_DAYSNUMBER_4("[WEATHER][TYPE1][numberOfDay][4][]"),
    WEATHER_DAYSNUMBER_5("[WEATHER][TYPE1][numberOfDay][5][]"),
    WEATHER_DAYSNUMBER_6("[WEATHER][TYPE1][numberOfDay][6][]"),
    WEATHER_DAYSNUMBER_7("[WEATHER][TYPE1][numberOfDay][7][]"),
    WEATHER_DAYSNUMBER_8("[WEATHER][TYPE1][numberOfDay][8][]"),
    WEATHER_DAYSNUMBER_9("[WEATHER][TYPE1][numberOfDay][9][]"),
    WEATHER_DAYSNUMBER_10("[WEATHER][TYPE1][numberOfDay][10][]"),
    WEATHER_DAYSNUMBER_11("[WEATHER][TYPE1][numberOfDay][11][]"),
    WEATHER_DAYSNUMBER_12("[WEATHER][TYPE1][numberOfDay][12][]"),
    WEATHER_DAYSNUMBER_13("[WEATHER][TYPE1][numberOfDay][13][]"),
    WEATHER_DAYSNUMBER_14("[WEATHER][TYPE1][numberOfDay][14][]"),
    WEATHER_DAYSNUMBER_15("[WEATHER][TYPE1][numberOfDay][15][]"),
    WEATHER_DAYSNUMBER_16("[WEATHER][TYPE1][numberOfDay][16][]"),
    WEATHER_DAYSNUMBER_17("[WEATHER][TYPE1][numberOfDay][17][]"),
    WEATHER_DAYSNUMBER_18("[WEATHER][TYPE1][numberOfDay][18][]"),
    WEATHER_DAYSNUMBER_19("[WEATHER][TYPE1][numberOfDay][19][]"),
    WEATHER_DAYSNUMBER_20("[WEATHER][TYPE1][numberOfDay][20][]"),
    WEATHER_DAYSNUMBER_21("[WEATHER][TYPE1][numberOfDay][21][]"),
    WEATHER_DAYSNUMBER_22("[WEATHER][TYPE1][numberOfDay][22][]"),
    WEATHER_DAYSNUMBER_23("[WEATHER][TYPE1][numberOfDay][23][]"),
    WEATHER_DAYSNUMBER_24("[WEATHER][TYPE1][numberOfDay][24][]"),
    WEATHER_DAYSNUMBER_25("[WEATHER][TYPE1][numberOfDay][25][]"),
    WEATHER_DAYSNUMBER_26("[WEATHER][TYPE1][numberOfDay][26][]"),
    WEATHER_DAYSNUMBER_27("[WEATHER][TYPE1][numberOfDay][27][]"),
    WEATHER_DAYSNUMBER_28("[WEATHER][TYPE1][numberOfDay][28][]"),
    WEATHER_DAYSNUMBER_29("[WEATHER][TYPE1][numberOfDay][29][]"),
    WEATHER_DAYSNUMBER_30("[WEATHER][TYPE1][numberOfDay][30][]"),
    WEATHER_DAYSNUMBER_31("[WEATHER][TYPE1][numberOfDay][31][]"),
    
    //parques
    PARQUE_BIBLIOTECA("[SAS][TYPE2][SUBTYPE3][Biblioteca]"),
    PARQUE_RESIDENCIAS("[SAS][TYPE2][SUBTYPE3][Residencias]"),
    PARQUE_SUBTERRANEO("[SAS][TYPE2][SUBTYPE3][Subterraneo]"),
    PARQUE_CERAMICA("[SAS][TYPE2][SUBTYPE3][Ceramica]"),
    PARQUE_LINGUAS("[SAS][TYPE2][SUBTYPE3][Linguas]"),
    PARQUE_INCUBADORA("[SAS][TYPE2][SUBTYPE3][Incubadora]"),
    PARQUE_ISCAAPUBLICO("[SAS][TYPE2][SUBTYPE3][ISCAA Publico]"),
    PARQUE_GERAL("[SAS][TYPE1][SUBTYPE1]"),

    CANTEENS_CRASTO_DAYSWEEK_DOMINGO("[CANTEENS][TYPE7][SUBTYPE1][Crasto][dayOfWeek][domingo][0]"),
    CANTEENS_CRASTO_DAYSWEEK_SEGUNDA("[CANTEENS][TYPE7][SUBTYPE1][Crasto][dayOfWeek][segunda][1]"),
    CANTEENS_CRASTO_DAYSWEEK_TERCA("[CANTEENS][TYPE7][SUBTYPE1][Crasto][dayOfWeek][terça][2]"),
    CANTEENS_CRASTO_DAYSWEEK_QUARTA("[CANTEENS][TYPE7][SUBTYPE1][Crasto][dayOfWeek][quarta][3]"),
    CANTEENS_CRASTO_DAYSWEEK_QUINTA("[CANTEENS][TYPE7][SUBTYPE1][Crasto][dayOfWeek][quinta][4]"),
    CANTEENS_CRASTO_DAYSWEEK_SEXTA("[CANTEENS][TYPE7][SUBTYPE1][Crasto][dayOfWeek][sexta][5]"),
    CANTEENS_CRASTO_DAYSWEEK_SABADO("[CANTEENS][TYPE7][SUBTYPE1][Crasto][dayOfWeek][sábado][6]"),
    
    //days relative
    CANTEENS_CRASTO_DAYSREL_TODAY("[CANTEENS][TYPE7][SUBTYPE1][Crasto][today][today][]"),
    CANTEENS_CRASTO_DAYSREL_TOMORROW("[CANTEENS][TYPE7][SUBTYPE1][Crasto][tomorrow][tomorrow][]"),
    
    //days number
    CANTEENS_CRASTO_DAYSNUMBER_1("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][1][]"),
    CANTEENS_CRASTO_DAYSNUMBER_2("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][2][]"),
    CANTEENS_CRASTO_DAYSNUMBER_3("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][3][]"),
    CANTEENS_CRASTO_DAYSNUMBER_4("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][4][]"),
    CANTEENS_CRASTO_DAYSNUMBER_5("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][5][]"),
    CANTEENS_CRASTO_DAYSNUMBER_6("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][6][]"),
    CANTEENS_CRASTO_DAYSNUMBER_7("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][7][]"),
    CANTEENS_CRASTO_DAYSNUMBER_8("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][8][]"),
    CANTEENS_CRASTO_DAYSNUMBER_9("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][9][]"),
    CANTEENS_CRASTO_DAYSNUMBER_10("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][10][]"),
    CANTEENS_CRASTO_DAYSNUMBER_11("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][11][]"),
    CANTEENS_CRASTO_DAYSNUMBER_12("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][12][]"),
    CANTEENS_CRASTO_DAYSNUMBER_13("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][13][]"),
    CANTEENS_CRASTO_DAYSNUMBER_14("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][14][]"),
    CANTEENS_CRASTO_DAYSNUMBER_15("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][15][]"),
    CANTEENS_CRASTO_DAYSNUMBER_16("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][16][]"),
    CANTEENS_CRASTO_DAYSNUMBER_17("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][17][]"),
    CANTEENS_CRASTO_DAYSNUMBER_18("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][18][]"),
    CANTEENS_CRASTO_DAYSNUMBER_19("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][19][]"),
    CANTEENS_CRASTO_DAYSNUMBER_20("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][20][]"),
    CANTEENS_CRASTO_DAYSNUMBER_21("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][21][]"),
    CANTEENS_CRASTO_DAYSNUMBER_22("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][22][]"),
    CANTEENS_CRASTO_DAYSNUMBER_23("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][23][]"),
    CANTEENS_CRASTO_DAYSNUMBER_24("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][24][]"),
    CANTEENS_CRASTO_DAYSNUMBER_25("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][25][]"),
    CANTEENS_CRASTO_DAYSNUMBER_26("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][26][]"),
    CANTEENS_CRASTO_DAYSNUMBER_27("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][27][]"),
    CANTEENS_CRASTO_DAYSNUMBER_28("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][28][]"),
    CANTEENS_CRASTO_DAYSNUMBER_29("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][29][]"),
    CANTEENS_CRASTO_DAYSNUMBER_30("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][30][]"),
    CANTEENS_CRASTO_DAYSNUMBER_31("[CANTEENS][TYPE7][SUBTYPE1][Crasto][numberOfDay][31][]"),
    
    
    //days week
    CANTEENS_SANTIAGO_DAYSWEEK_DOMINGO("[CANTEENS][TYPE7][SUBTYPE1][Santiago][dayOfWeek][domingo][0]"),
    CANTEENS_SANTIAGO_DAYSWEEK_SEGUNDA("[CANTEENS][TYPE7][SUBTYPE1][Santiago][dayOfWeek][segunda][1]"),
    CANTEENS_SANTIAGO_DAYSWEEK_TERCA("[CANTEENS][TYPE7][SUBTYPE1][Santiago][dayOfWeek][terça][2]"),
    CANTEENS_SANTIAGO_DAYSWEEK_QUARTA("[CANTEENS][TYPE7][SUBTYPE1][Santiago][dayOfWeek][quarta][3]"),
    CANTEENS_SANTIAGO_DAYSWEEK_QUINTA("[CANTEENS][TYPE7][SUBTYPE1][Santiago][dayOfWeek][quinta][4]"),
    CANTEENS_SANTIAGO_DAYSWEEK_SEXTA("[CANTEENS][TYPE7][SUBTYPE1][Santiago][dayOfWeek][sexta][5]"),
    CANTEENS_SANTIAGO_DAYSWEEK_SABADO("[CANTEENS][TYPE7][SUBTYPE1][Santiago][dayOfWeek][sábado][6]"),
    
    //days relative
    CANTEENS_SANTIAGO_DAYSREL_TODAY("[CANTEENS][TYPE7][SUBTYPE1][Santiago][today][today][]"),
    CANTEENS_SANTIAGO_DAYSREL_TOMORROW("[CANTEENS][TYPE7][SUBTYPE1][Santiago][tomorrow][tomorrow][]"),
    
    //days number
    CANTEENS_SANTIAGO_DAYSNUMBER_1("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][1][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_2("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][2][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_3("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][3][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_4("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][4][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_5("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][5][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_6("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][6][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_7("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][7][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_8("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][8][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_9("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][9][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_10("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][10][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_11("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][11][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_12("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][12][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_13("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][13][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_14("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][14][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_15("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][15][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_16("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][16][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_17("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][17][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_18("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][18][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_19("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][19][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_20("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][20][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_21("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][21][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_22("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][22][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_23("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][23][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_24("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][24][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_25("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][25][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_26("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][26][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_27("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][27][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_28("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][28][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_29("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][29][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_30("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][30][]"),
    CANTEENS_SANTIAGO_DAYSNUMBER_31("[CANTEENS][TYPE7][SUBTYPE1][Santiago][numberOfDay][31][]"),
    
    CANTEENS_CRASTO("[CANTEENS][TYPE7][SUBTYPE1][Crasto][today][today][]"),
    CANTEENS_SANTIAGO("[CANTEENS][TYPE7][SUBTYPE1][Santiago][today][today][]"),
    
    //days week
    CANTEENS_DAYSWEEK_DOMINGO("[CANTEENS][TYPE7][SUBTYPE2][dayOfWeek][domingo][0]"),
    CANTEENS_DAYSWEEK_SEGUNDA("[CANTEENS][TYPE7][SUBTYPE2][dayOfWeek][segunda][1]"),
    CANTEENS_DAYSWEEK_TERCA("[CANTEENS][TYPE7][SUBTYPE2][dayOfWeek][terça][2]"),
    CANTEENS_DAYSWEEK_QUARTA("[CANTEENS][TYPE7][SUBTYPE2][dayOfWeek][quarta][3]"),
    CANTEENS_DAYSWEEK_QUINTA("[CANTEENS][TYPE7][SUBTYPE2][dayOfWeek][quinta][4]"),
    CANTEENS_DAYSWEEK_SEXTA("[CANTEENS][TYPE7][SUBTYPE2][dayOfWeek][sexta][5]"),
    CANTEENS_DAYSWEEK_SABADO("[CANTEENS][TYPE7][SUBTYPE2][dayOfWeek][sábado][6]"),
    
    //days relative
    CANTEENS_DAYSREL_TODAY("[CANTEENS][TYPE7][SUBTYPE2][today][today][]"),
    CANTEENS_DAYSREL_TOMORROW("[CANTEENS][TYPE7][SUBTYPE2][tomorrow][tomorrow][]"),
    
    //days number
    CANTEENS_DAYSNUMBER_1("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][1][]"),
    CANTEENS_DAYSNUMBER_2("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][2][]"),
    CANTEENS_DAYSNUMBER_3("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][3][]"),
    CANTEENS_DAYSNUMBER_4("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][4][]"),
    CANTEENS_DAYSNUMBER_5("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][5][]"),
    CANTEENS_DAYSNUMBER_6("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][6][]"),
    CANTEENS_DAYSNUMBER_7("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][7][]"),
    CANTEENS_DAYSNUMBER_8("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][8][]"),
    CANTEENS_DAYSNUMBER_9("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][9][]"),
    CANTEENS_DAYSNUMBER_10("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][10][]"),
    CANTEENS_DAYSNUMBER_11("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][11][]"),
    CANTEENS_DAYSNUMBER_12("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][12][]"),
    CANTEENS_DAYSNUMBER_13("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][13][]"),
    CANTEENS_DAYSNUMBER_14("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][14][]"),
    CANTEENS_DAYSNUMBER_15("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][15][]"),
    CANTEENS_DAYSNUMBER_16("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][16][]"),
    CANTEENS_DAYSNUMBER_17("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][17][]"),
    CANTEENS_DAYSNUMBER_18("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][18][]"),
    CANTEENS_DAYSNUMBER_19("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][19][]"),
    CANTEENS_DAYSNUMBER_20("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][20][]"),
    CANTEENS_DAYSNUMBER_21("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][21][]"),
    CANTEENS_DAYSNUMBER_22("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][22][]"),
    CANTEENS_DAYSNUMBER_23("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][23][]"),
    CANTEENS_DAYSNUMBER_24("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][24][]"),
    CANTEENS_DAYSNUMBER_25("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][25][]"),
    CANTEENS_DAYSNUMBER_26("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][26][]"),
    CANTEENS_DAYSNUMBER_27("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][27][]"),
    CANTEENS_DAYSNUMBER_28("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][28][]"),
    CANTEENS_DAYSNUMBER_29("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][29][]"),
    CANTEENS_DAYSNUMBER_30("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][30][]"),
    CANTEENS_DAYSNUMBER_31("[CANTEENS][TYPE7][SUBTYPE2][numberOfDay][31][]"),  
    CANTEENS_GERAL("[CANTEENS][TYPE5]"),
    
    
    
    SENHAS_FILA_A("[SAC][TYPE7][A][A]"),
    SENHAS_FILA_LICENCIATURA("[SAC][TYPE7][A][de(_)licenciatura]"),
    SENHAS_FILA_MESTRADO("[SAC][TYPE7][A][de(_)mestrado]"),
    SENHAS_FILA_LICENCIATURA_MESTRADO("[SAC][TYPE7][A][de(_)licenciatura(_)e(_)mestrado]"),
    SENHAS_FILA_C("[SAC][TYPE7][C][C]"),
    SENHAS_FILA_DOUTORAMENTO("[SAC][TYPE7][C][de(_)doutoramento]"),
    SENHAS_FILA_AGREGACOES("[SAC][TYPE7][C][de(_)agrega(c)(o_till)es]"),
    SENHAS_FILA_DOUTORAMENTO_AGREGACOES("[SAC][TYPE7][C][de(_)doutoramento(_)e(_)agrega(c)(o_till)es]"),
    SENHAS_FILA_D("[SAC][TYPE7][D][D]"),
    SENHAS_FILA_PRIORITARIO("[SAC][TYPE7][D][de(_)atendimento(_)priorit(a_acent)rio]"),
    SENHAS_FILA_F("[SAC][TYPE7][F][F]"),
    SENHAS_FILA_PROFISSIONAL("[SAC][TYPE7][F][de(_)inserção(_)profissional]"),
    SENHAS_FILA_G("[SAC][TYPE7][G][G]"),
    SENHAS_FILA_MODALIDADE_ERASMUS("[SAC][TYPE7][G][de(_)mobilidade(_)erasmus]"),
    SENHAS_FILA_ERASMUS("[SAC][TYPE7][G][de_erasmus]"),
    SENHAS_FILA_H("[SAC][TYPE7][H][H]"),
    SENHAS_FILA_ESTAGIOS("[SAC][TYPE7][H][de(_)est(a_acent)gios(_)internacionais]"),
    SENHAS_FILA_X("[SAC][TYPE7][X][X]"),
    SENHAS_FILA_EXCHANGE("[SAC][TYPE7][X][de(_)exchange]"),
    SENHAS_FILA_INTERCAMBIO("[SAC][TYPE7][X][de(_)interc(a_cir)mbio]"),

    SENHAS_GERAL("[SAC][TYPE1]"),
    GERAL_PASS_DONT_RECOGNIZE("[NOTRECOGNIZE]") 
    
    //GERAL_PASS_DONT_RECOGNIZE("[NOTRECOGNIZE]")
    ;
    
    
    
    private final String event;

    Output(String m) {
        event=m;
    }
    
    @Override
    public String getEvent(){
        return this.toString();
    }

    @Override
    public String getEventName(){
        return event;
    }
}
