/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import genfusionscxml.GenFusionSCXML;
import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  
    
    //days week
    DAYSWEEK_DOMINGO("[dayOfWeek][domingo][0]",GenFusionSCXML.TIMEOUT),
    DAYSWEEK_SEGUNDA("[dayOfWeek][segunda][1]",GenFusionSCXML.TIMEOUT),
    DAYSWEEK_TERCA("[dayOfWeek][terça][2]",GenFusionSCXML.TIMEOUT),
    DAYSWEEK_QUARTA("[dayOfWeek][quarta][3]",GenFusionSCXML.TIMEOUT),
    DAYSWEEK_QUINTA("[dayOfWeek][quinta][4]",GenFusionSCXML.TIMEOUT),
    DAYSWEEK_SEXTA("[dayOfWeek][sexta][5]",GenFusionSCXML.TIMEOUT),
    DAYSWEEK_SABADO("[dayOfWeek][sábado][6]",GenFusionSCXML.TIMEOUT),
    
    //days relative
    DAYSREL_TODAY("[today][today][]",GenFusionSCXML.TIMEOUT),
    DAYSREL_TOMORROW("[tomorrow][tomorrow][]",GenFusionSCXML.TIMEOUT),
    
    //days number
    DAYSNUMBER_1("[numberOfDay][1][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_2("[numberOfDay][2][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_3("[numberOfDay][3][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_4("[numberOfDay][4][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_5("[numberOfDay][5][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_6("[numberOfDay][6][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_7("[numberOfDay][7][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_8("[numberOfDay][8][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_9("[numberOfDay][9][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_10("[numberOfDay][10][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_11("[numberOfDay][11][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_12("[numberOfDay][12][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_13("[numberOfDay][13][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_14("[numberOfDay][14][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_15("[numberOfDay][15][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_16("[numberOfDay][16][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_17("[numberOfDay][17][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_18("[numberOfDay][18][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_19("[numberOfDay][19][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_20("[numberOfDay][20][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_21("[numberOfDay][21][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_22("[numberOfDay][22][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_23("[numberOfDay][23][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_24("[numberOfDay][24][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_25("[numberOfDay][25][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_26("[numberOfDay][26][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_27("[numberOfDay][27][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_28("[numberOfDay][28][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_29("[numberOfDay][29][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_30("[numberOfDay][30][]",GenFusionSCXML.TIMEOUT),
    DAYSNUMBER_31("[numberOfDay][31][]",GenFusionSCXML.TIMEOUT),
    
    //parques
    PARQUE_BIBLIOTECA("[Biblioteca]",GenFusionSCXML.TIMEOUT),
    PARQUE_RESIDENCIAS("[Residencias]",GenFusionSCXML.TIMEOUT),
    PARQUE_SUBTERRANEO("[Subterraneo]",GenFusionSCXML.TIMEOUT),
    PARQUE_CERAMICA("[Ceramica]",GenFusionSCXML.TIMEOUT),
    PARQUE_LINGUAS("[Linguas]",GenFusionSCXML.TIMEOUT),
    PARQUE_INCUBADORA("[Incubadora]",GenFusionSCXML.TIMEOUT),
    PARQUE_ISCAAPUBLICO("[ISCAA]",GenFusionSCXML.TIMEOUT),
    
    //Canteens
    CANTEENS_CRASTO("[CANTEENS][TYPE5][Crasto]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO("[CANTEENS][TYPE5][Santiago]",GenFusionSCXML.TIMEOUT),
    
    //days week
    CANTEENS_CRASTO_DAYSWEEK_DOMINGO("[CANTEENS][TYPE5][Crasto][dayOfWeek][domingo][0]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSWEEK_SEGUNDA("[CANTEENS][TYPE5][Crasto][dayOfWeek][segunda][1]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSWEEK_TERCA("[CANTEENS][TYPE5][Crasto][dayOfWeek][terça][2]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSWEEK_QUARTA("[CANTEENS][TYPE5][Crasto][dayOfWeek][quarta][3]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSWEEK_QUINTA("[CANTEENS][TYPE5][Crasto][dayOfWeek][quinta][4]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSWEEK_SEXTA("[CANTEENS][TYPE5][Crasto][dayOfWeek][sexta][5]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSWEEK_SABADO("[CANTEENS][TYPE5][Crasto][dayOfWeek][sábado][6]",GenFusionSCXML.TIMEOUT),
    
    //days relative
    CANTEENS_CRASTO_DAYSREL_TODAY("[CANTEENS][TYPE5][Crasto][today][today][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSREL_TOMORROW("[CANTEENS][TYPE5][Crasto][tomorrow][tomorrow][]",GenFusionSCXML.TIMEOUT),
    
    //days number
    CANTEENS_CRASTO_DAYSNUMBER_1("[CANTEENS][TYPE5][Crasto][numberOfDay][1][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_2("[CANTEENS][TYPE5][Crasto][numberOfDay][2][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_3("[CANTEENS][TYPE5][Crasto][numberOfDay][3][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_4("[CANTEENS][TYPE5][Crasto][numberOfDay][4][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_5("[CANTEENS][TYPE5][Crasto][numberOfDay][5][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_6("[CANTEENS][TYPE5][Crasto][numberOfDay][6][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_7("[CANTEENS][TYPE5][Crasto][numberOfDay][7][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_8("[CANTEENS][TYPE5][Crasto][numberOfDay][8][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_9("[CANTEENS][TYPE5][Crasto][numberOfDay][9][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_10("[CANTEENS][TYPE5][Crasto][numberOfDay][10][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_11("[CANTEENS][TYPE5][Crasto][numberOfDay][11][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_12("[CANTEENS][TYPE5][Crasto][numberOfDay][12][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_13("[CANTEENS][TYPE5][Crasto][numberOfDay][13][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_14("[CANTEENS][TYPE5][Crasto][numberOfDay][14][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_15("[CANTEENS][TYPE5][Crasto][numberOfDay][15][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_16("[CANTEENS][TYPE5][Crasto][numberOfDay][16][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_17("[CANTEENS][TYPE5][Crasto][numberOfDay][17][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_18("[CANTEENS][TYPE5][Crasto][numberOfDay][18][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_19("[CANTEENS][TYPE5][Crasto][numberOfDay][19][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_20("[CANTEENS][TYPE5][Crasto][numberOfDay][20][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_21("[CANTEENS][TYPE5][Crasto][numberOfDay][21][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_22("[CANTEENS][TYPE5][Crasto][numberOfDay][22][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_23("[CANTEENS][TYPE5][Crasto][numberOfDay][23][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_24("[CANTEENS][TYPE5][Crasto][numberOfDay][24][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_25("[CANTEENS][TYPE5][Crasto][numberOfDay][25][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_26("[CANTEENS][TYPE5][Crasto][numberOfDay][26][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_27("[CANTEENS][TYPE5][Crasto][numberOfDay][27][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_28("[CANTEENS][TYPE5][Crasto][numberOfDay][28][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_29("[CANTEENS][TYPE5][Crasto][numberOfDay][29][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_30("[CANTEENS][TYPE5][Crasto][numberOfDay][30][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_CRASTO_DAYSNUMBER_31("[CANTEENS][TYPE5][Crasto][numberOfDay][31][]",GenFusionSCXML.TIMEOUT),
    
    //days week
    CANTEENS_SANTIAGO_DAYSWEEK_DOMINGO("[CANTEENS][TYPE5][Santiago][dayOfWeek][domingo][0]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSWEEK_SEGUNDA("[CANTEENS][TYPE5][Santiago][dayOfWeek][segunda][1]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSWEEK_TERCA("[CANTEENS][TYPE5][Santiago][dayOfWeek][terça][2]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSWEEK_QUARTA("[CANTEENS][TYPE5][Santiago][dayOfWeek][quarta][3]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSWEEK_QUINTA("[CANTEENS][TYPE5][Santiago][dayOfWeek][quinta][4]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSWEEK_SEXTA("[CANTEENS][TYPE5][Santiago][dayOfWeek][sexta][5]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSWEEK_SABADO("[CANTEENS][TYPE5][Santiago][dayOfWeek][sábado][6]",GenFusionSCXML.TIMEOUT),
    
    //days relative
    CANTEENS_SANTIAGO_DAYSREL_TODAY("[CANTEENS][TYPE5][Santiago][today][today][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSREL_TOMORROW("[CANTEENS][TYPE5][Santiago][tomorrow][tomorrow][]",GenFusionSCXML.TIMEOUT),
    
    //days number
    CANTEENS_SANTIAGO_DAYSNUMBER_1("[CANTEENS][TYPE5][Santiago][numberOfDay][1][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_2("[CANTEENS][TYPE5][Santiago][numberOfDay][2][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_3("[CANTEENS][TYPE5][Santiago][numberOfDay][3][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_4("[CANTEENS][TYPE5][Santiago][numberOfDay][4][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_5("[CANTEENS][TYPE5][Santiago][numberOfDay][5][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_6("[CANTEENS][TYPE5][Santiago][numberOfDay][6][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_7("[CANTEENS][TYPE5][Santiago][numberOfDay][7][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_8("[CANTEENS][TYPE5][Santiago][numberOfDay][8][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_9("[CANTEENS][TYPE5][Santiago][numberOfDay][9][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_10("[CANTEENS][TYPE5][Santiago][numberOfDay][10][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_11("[CANTEENS][TYPE5][Santiago][numberOfDay][11][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_12("[CANTEENS][TYPE5][Santiago][numberOfDay][12][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_13("[CANTEENS][TYPE5][Santiago][numberOfDay][13][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_14("[CANTEENS][TYPE5][Santiago][numberOfDay][14][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_15("[CANTEENS][TYPE5][Santiago][numberOfDay][15][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_16("[CANTEENS][TYPE5][Santiago][numberOfDay][16][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_17("[CANTEENS][TYPE5][Santiago][numberOfDay][17][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_18("[CANTEENS][TYPE5][Santiago][numberOfDay][18][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_19("[CANTEENS][TYPE5][Santiago][numberOfDay][19][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_20("[CANTEENS][TYPE5][Santiago][numberOfDay][20][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_21("[CANTEENS][TYPE5][Santiago][numberOfDay][21][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_22("[CANTEENS][TYPE5][Santiago][numberOfDay][22][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_23("[CANTEENS][TYPE5][Santiago][numberOfDay][23][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_24("[CANTEENS][TYPE5][Santiago][numberOfDay][24][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_25("[CANTEENS][TYPE5][Santiago][numberOfDay][25][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_26("[CANTEENS][TYPE5][Santiago][numberOfDay][26][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_27("[CANTEENS][TYPE5][Santiago][numberOfDay][27][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_28("[CANTEENS][TYPE5][Santiago][numberOfDay][28][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_29("[CANTEENS][TYPE5][Santiago][numberOfDay][29][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_30("[CANTEENS][TYPE5][Santiago][numberOfDay][30][]",GenFusionSCXML.TIMEOUT),
    CANTEENS_SANTIAGO_DAYSNUMBER_31("[CANTEENS][TYPE5][Santiago][numberOfDay][31][]",GenFusionSCXML.TIMEOUT),
    
    
    //
    //SENHAS_FILA_INTERCAMBIO("[X][de_interc(a_cir)mbio]",GenFusionSCXML.TIMEOUT),
    //SENHAS_FILA_DOUTORAMENTO("[C][de_doutoramento]",GenFusionSCXML.TIMEOUT),
    
    SENHAS_FILA_A("[A][A]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_LICENCIATURA("[A][de(_)licenciatura]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_MESTRADO("[A][de(_)mestrado]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_LICENCIATURA_MESTRADO("[A][de(_)licenciatura(_)e(_)mestrado]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_C("[C][C]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_DOUTORAMENTO("[C][de(_)doutoramento]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_AGREGACOES("[C][de(_)agrega(c)(o_till)es]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_DOUTORAMENTO_AGREGACOES("[C][de(_)doutoramento(_)e(_)agrega(c)(o_till)es]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_D("[D][D]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_PRIORITARIO("[D][de(_)atendimento(_)priorit(a_acent)rio]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_F("[F][F]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_PROFISSIONAL("[F][de(_)inserção(_)profissional]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_G("[G][G]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_MODALIDADE_ERASMUS("[G][de(_)mobilidade(_)erasmus]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_ERASMUS("[G][de_erasmus]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_H("[H][H]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_ESTAGIOS("[H][de(_)est(a_acent)gios(_)internacionais]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_X("[X][X]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_EXCHANGE("[X][de(_)exchange]",GenFusionSCXML.TIMEOUT),
    SENHAS_FILA_INTERCAMBIO("[X][de(_)interc(a_cir)mbio]",GenFusionSCXML.TIMEOUT),
    
    
    ;

 
    private String event; 
    private int timeout;
    Speech(String m, int time) {
            event=m;
            timeout=time;
    }
    @Override
    public int getTimeOut(){
            return timeout;
    }
    @Override
    public String getEventName(){
            return event;
    }
    @Override
    public String getEvName(){
            return getModalityName().toLowerCase() +event.toLowerCase();
    }

}
