/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

        DAYS_DOMINGO("[dayOfWeek][domingo][0]",1500),
        DAYS_SEGUNDA("[dayOfWeek][segunda][1]",1500),
        DAYS_TERCA("[dayOfWeek][terça][2]",1500),
        DAYS_QUARTA("[dayOfWeek][quarta][3]",1500),
        DAYS_QUINTA("[dayOfWeek][quinta][4]",1500),
        DAYS_SEXTA("[dayOfWeek][sexta][5]",1500),
        DAYS_SABADO("[dayOfWeek][sábado][6]",1500),
	PARQUES_LUGARES_LINGUAS("[SAS][TYPE2][SUBTYPE3][Linguas]",1500),
        TRIANGLE("[shape][TRIANGLE]",1500),
        CIRCLE("[shape][CIRCLE]",1500),
        CIRCLE_RED("[shape][CIRCLE][color][RED]",1500);


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
